// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0mXuuyuaHNmefQq1ReMPsFurc04VQcM',
    appId: '1:739890274129:web:f75146c5734b424664fd70',
    messagingSenderId: '739890274129',
    projectId: 'pos-application-b0d83',
    authDomain: 'pos-application-b0d83.firebaseapp.com',
    storageBucket: 'pos-application-b0d83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5zMGOCO6tk2JPlkvt0sFC6m9gkwXE8og',
    appId: '1:739890274129:android:8821c2f3eb960e0a64fd70',
    messagingSenderId: '739890274129',
    projectId: 'pos-application-b0d83',
    storageBucket: 'pos-application-b0d83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW3zw_PjBRMY2rvYQOiH6uEv8ryFHuofM',
    appId: '1:739890274129:ios:7b51711a86897f8164fd70',
    messagingSenderId: '739890274129',
    projectId: 'pos-application-b0d83',
    storageBucket: 'pos-application-b0d83.appspot.com',
    iosBundleId: 'com.example.myPosQue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW3zw_PjBRMY2rvYQOiH6uEv8ryFHuofM',
    appId: '1:739890274129:ios:5a9cd8e38496413b64fd70',
    messagingSenderId: '739890274129',
    projectId: 'pos-application-b0d83',
    storageBucket: 'pos-application-b0d83.appspot.com',
    iosBundleId: 'com.example.myPosQue.RunnerTests',
  );
}
